"""add phase2 deploy engine tables

Revision ID: 7c6c3df56972
Revises: 55e9d375362c
Create Date: 2026-04-11 10:21:04.135394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6c3df56972'
down_revision: Union[str, None] = '55e9d375362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('docker_host', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DRAINING', 'MAINTENANCE', name='nodestatus'), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('container_count', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=True)
    op.create_table('container',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'PAUSED', 'RESTARTING', 'EXITED', 'DEAD', name='containerstatus'), nullable=True),
    sa.Column('ports', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('resource_limits', sa.JSON(), nullable=True),
    sa.Column('health_check', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['project_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_container_id'), 'container', ['container_id'], unique=True)
    op.create_index(op.f('ix_container_name'), 'container', ['name'], unique=False)
    op.create_table('deploy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('strategy', sa.Enum('BLUE_GREEN', 'ROLLING', 'RECREATE', name='deploystrategy'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'DEPLOYING', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploystatus'), nullable=True),
    sa.Column('target_env', sa.String(length=32), nullable=True),
    sa.Column('node_id', sa.BigInteger(), nullable=True),
    sa.Column('container_ids', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('deployed_by', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['project_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploy')
    op.drop_index(op.f('ix_container_name'), table_name='container')
    op.drop_index(op.f('ix_container_container_id'), table_name='container')
    op.drop_table('container')
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
