"""add spider table

Revision ID: b6985578c953
Revises: 7c6c3df56972
Create Date: 2026-04-11 23:38:30.548986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6985578c953'
down_revision: Union[str, None] = '7c6c3df56972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 与 4a8c26e16402 并行分支：建表/加列/删表均幂等
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    dialect = bind.dialect.name.lower()

    def _has_index(table_name: str, index_name: str) -> bool:
        try:
            indexes = inspector.get_indexes(table_name)
        except Exception:
            return False
        return any(i['name'] == index_name for i in indexes)

    if not inspector.has_table('spider'):
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('spider',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('project_id', sa.BigInteger(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('spider_type', sa.Enum('SCRAPY', 'SELENIUM', 'PLAYWRIGHT', 'REQUESTS', 'CUSTOM', name='spidertype'), nullable=True),
        sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', 'ERROR', name='spiderstatus'), nullable=True),
        sa.Column('git_url', sa.String(length=512), nullable=True),
        sa.Column('git_auth_type', sa.String(length=32), nullable=True),
        sa.Column('git_username', sa.String(length=128), nullable=True),
        sa.Column('git_password', sa.String(length=256), nullable=True),
        sa.Column('git_ssh_key', sa.Text(), nullable=True),
        sa.Column('git_passphrase', sa.String(length=256), nullable=True),
        sa.Column('git_branch', sa.String(length=128), nullable=True),
        sa.Column('code_path', sa.String(length=512), nullable=True),
        sa.Column('entry_file', sa.String(length=256), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('schedule_config', sa.JSON(), nullable=True),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('last_run_status', sa.String(length=32), nullable=True),
        sa.Column('run_count', sa.Integer(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('error_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_spider_name'), 'spider', ['name'], unique=False)

    # 幂等删除：不存在的 index/table 直接跳过（另一并行分支可能已删，或新库根本就没这些表）
    def _drop_table_if_exists(name: str):
        if inspector.has_table(name):
            op.drop_table(name)

    def _drop_index_if_exists(index_name: str, table_name: str):
        if inspector.has_table(table_name) and _has_index(table_name, index_name):
            op.drop_index(index_name, table_name=table_name)

    _drop_index_if_exists('ix_api_call_log_called_at', 'api_call_log')
    _drop_table_if_exists('api_call_log')
    _drop_index_if_exists('ix_api_rate_limit_window_start', 'api_rate_limit')
    _drop_table_if_exists('api_rate_limit')
    _drop_index_if_exists('ix_data_quality_check_spider_name', 'data_quality_check')
    _drop_table_if_exists('data_quality_check')
    _drop_index_if_exists('ix_data_statistics_project_id', 'data_statistics')
    _drop_index_if_exists('ix_data_statistics_spider_name', 'data_statistics')
    _drop_index_if_exists('ix_data_statistics_stat_date', 'data_statistics')
    _drop_table_if_exists('data_statistics')
    _drop_index_if_exists('ix_data_quality_rule_spider_name', 'data_quality_rule')
    _drop_table_if_exists('data_quality_rule')
    _drop_index_if_exists('ix_proxy_check_log_checked_at', 'proxy_check_log')
    _drop_table_if_exists('proxy_check_log')
    _drop_table_if_exists('proxy_usage_log')
    _drop_index_if_exists('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs')
    _drop_table_if_exists('apscheduler_jobs')

    columns = {c['name'] for c in inspector.get_columns('task_instance')}
    if 'spider_id' not in columns:
        # SQLite 不支持 CREATE TABLE 后的 ADD CONSTRAINT (FK)，需 batch_alter_table；
        # 生产 MySQL/PostgreSQL 允许。先加列，再尝试加 FK（失败跳过，应用层 ORM 仍可工作）。
        op.add_column('task_instance', sa.Column('spider_id', sa.BigInteger(), nullable=True))
        try:
            if dialect.startswith('sqlite'):
                with op.batch_alter_table('task_instance') as batch_op:
                    batch_op.create_foreign_key(None, 'spider', ['spider_id'], ['id'])
            else:
                op.create_foreign_key(None, 'task_instance', 'spider', ['spider_id'], ['id'])
        except Exception:
            import logging as _log
            _log.getLogger(__name__).warning(
                '跳过 task_instance.spider_id FK 创建（SQLite 不支持 ALTER ADD CONSTRAINT）',
                exc_info=True,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_instance', type_='foreignkey')
    op.drop_column('task_instance', 'spider_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('proxy_usage_log',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('proxy_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('task_instance_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('request_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('success_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('failed_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_response_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='proxy_usage_log_ibfk_2'),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy_pool.id'], name='proxy_usage_log_ibfk_1'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], name='proxy_usage_log_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proxy_check_log',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('proxy_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('response_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('health_score_before', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('health_score_after', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('checked_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy_pool.id'], name='proxy_check_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_proxy_check_log_checked_at', 'proxy_check_log', ['checked_at'], unique=False)
    op.create_table('data_quality_rule',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('spider_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('rule_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('rule_type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('conditions', mysql.JSON(), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='data_quality_rule_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_data_quality_rule_spider_name', 'data_quality_rule', ['spider_name'], unique=False)
    op.create_table('data_statistics',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('spider_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('task_instance_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('total_records', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('increment_records', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('data_size_bytes', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('avg_response_time', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('success_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('stat_date', mysql.DATETIME(), nullable=False),
    sa.Column('stat_type', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('data_source', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='data_statistics_ibfk_1'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], name='data_statistics_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_data_statistics_stat_date', 'data_statistics', ['stat_date'], unique=False)
    op.create_index('ix_data_statistics_spider_name', 'data_statistics', ['spider_name'], unique=False)
    op.create_index('ix_data_statistics_project_id', 'data_statistics', ['project_id'], unique=False)
    op.create_table('data_quality_check',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('task_instance_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('spider_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('total_records', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('expected_min_records', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('expected_max_records', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('records_in_range', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('null_fields', mysql.JSON(), nullable=True),
    sa.Column('null_rate_threshold', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('null_rate_passed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('duplicate_count', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('duplicate_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('duplicate_rate_threshold', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('duplicate_passed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('format_errors', mysql.JSON(), nullable=True),
    sa.Column('format_passed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('data_freshness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('freshness_threshold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('freshness_passed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('overall_status', mysql.ENUM('PASSED', 'WARNING', 'FAILED'), nullable=True),
    sa.Column('score', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('details', mysql.JSON(), nullable=True),
    sa.Column('checked_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='data_quality_check_ibfk_2'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], name='data_quality_check_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_data_quality_check_spider_name', 'data_quality_check', ['spider_name'], unique=False)
    op.create_table('api_rate_limit',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('api_config_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('window_start', mysql.DATETIME(), nullable=False),
    sa.Column('window_end', mysql.DATETIME(), nullable=False),
    sa.Column('request_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('limit_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_limited', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_config.id'], name='api_rate_limit_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_api_rate_limit_window_start', 'api_rate_limit', ['window_start'], unique=False)
    op.create_table('api_call_log',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('api_config_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('task_instance_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('endpoint', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('method', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('response_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('request_size', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('response_size', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('is_success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('circuit_breaker_open', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('consecutive_failures', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('called_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_config.id'], name='api_call_log_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='api_call_log_ibfk_2'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instance.id'], name='api_call_log_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_api_call_log_called_at', 'api_call_log', ['called_at'], unique=False)
    op.drop_index(op.f('ix_spider_name'), table_name='spider')
    op.drop_table('spider')
    # ### end Alembic commands ###
